In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [19]:
text_cols = ["Sex", "ChestPainType", "FastingBS", "RestingECG", "ExerciseAngina", "ST_Slope", "HeartDisease"]
numdf = df.drop(text_cols, axis=1)
numdf

     Age  RestingBP  Cholesterol  MaxHR  Oldpeak
0     40        140          289    172      0.0
1     49        160          180    156      1.0
2     37        130          283     98      0.0
3     48        138          214    108      1.5
4     54        150          195    122      0.0
..   ...        ...          ...    ...      ...
913   45        110          264    132      1.2
914   68        144          193    141      3.4
915   57        130          131    115      1.2
916   57        130          236    174      0.0
917   38        138          175    173      0.0

[918 rows x 5 columns]

In [18]:
import numpy as np

z_scores = np.abs((num_df - numdf.mean()) / numdf.std())
threshold = 3
outliers = (z_scores > threshold).any(axis=1)

numdf_no_outliers = numdf[~outliers]

print(numdf_no_outliers)

     Age  RestingBP  Cholesterol  MaxHR  Oldpeak
0     40        140          289    172      0.0
1     49        160          180    156      1.0
2     37        130          283     98      0.0
3     48        138          214    108      1.5
4     54        150          195    122      0.0
..   ...        ...          ...    ...      ...
913   45        110          264    132      1.2
914   68        144          193    141      3.4
915   57        130          131    115      1.2
916   57        130          236    174      0.0
917   38        138          175    173      0.0

[899 rows x 5 columns]

In [28]:
scaled_df = pd.concat([numdf_no_outliers, df[text_cols]], axis=1).dropna()

In [32]:
scaled_df = pd.get_dummies(scaled_df, drop_first=True)
scaled_df

,Age,RestingBP,Cholesterol,MaxHR,Oldpeak,FastingBS,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40.0,140.0,289.0,172.0,0.0,0,0,True,True,False,False,True,False,False,False,True
1,49.0,160.0,180.0,156.0,1.0,0,1,False,False,True,False,True,False,False,True,False
2,37.0,130.0,283.0,98.0,0.0,0,0,True,True,False,False,False,True,False,False,True
3,48.0,138.0,214.0,108.0,1.5,0,1,False,False,False,False,True,False,True,True,False
4,54.0,150.0,195.0,122.0,0.0,0,0,True,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,110.0,264.0,132.0,1.2,0,1,True,False,False,True,True,False,False,True,False
914,68.0,144.0,193.0,141.0,3.4,1,1,True,False,False,False,True,False,False,True,False
915,57.0,130.0,131.0,115.0,1.2,0,1,True,False,False,False,True,False,True,True,False
916,57.0,130.0,236.0,174.0,0.0,0,1,False,True,False,False,False,False,False,True,False
917,38.0,138.0,175.0,173.0,0.0,0,0,True,False,True,False,True,False,False,False,True

In [34]:
X = scaled_df.drop(["HeartDisease"], axis=1)
y = scaled_df["HeartDisease"]

In [35]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [36]:
x = scaler.fit_transform(X)
x

array([[-1.42815446,  0.46590022,  0.84963584, ..., -0.8229452 ,
        -0.99888827,  1.13469459],
       [-0.47585532,  1.63471366, -0.16812204, ..., -0.8229452 ,
         1.00111297, -0.88129441],
       [-1.7455875 , -0.1185065 ,  0.79361247, ..., -0.8229452 ,
        -0.99888827,  1.13469459],
       ...,
       [ 0.3706328 , -0.1185065 , -0.62564622, ...,  1.21514774,
         1.00111297, -0.88129441],
       [ 0.3706328 , -0.1185065 ,  0.35476274, ..., -0.8229452 ,
         1.00111297, -0.88129441],
       [-1.63977649,  0.34901888, -0.21480818, ..., -0.8229452 ,
        -0.99888827,  1.13469459]])

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [41]:
X_train.shape

(719, 15)

In [42]:
X_test.shape

(180, 15)

In [43]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()
model_rf.fit(X_train, y_train)
model_rf.score(X_test, y_test)

0.9

In [44]:
from sklearn.decomposition import PCA

pca = PCA()
X_pca = pca.fit_transform(X)
X_pca

array([[ 9.31296215e+01, -2.96791460e+01,  1.09495159e+01, ...,
         8.80755875e-03,  1.24535136e-02,  2.77849028e-02],
       [-1.63385163e+01, -1.47998355e+01,  3.10879247e+01, ...,
        -1.02429834e-01, -3.74435786e-02,  5.49090365e-02],
       [ 8.26696266e+01,  3.89118718e+01, -1.47874603e+01, ...,
        -4.77352754e-02,  1.09771770e-01,  8.82409779e-03],
       ...,
       [-6.82260863e+01,  1.76979471e+01, -4.33471292e+00, ...,
        -4.06273119e-02, -2.15328912e-02, -5.56702859e-02],
       [ 4.00262424e+01, -3.34650307e+01,  5.36031095e+00, ...,
         4.78927100e-01, -8.66489494e-03,  7.54023492e-02],
       [-2.06125201e+01, -3.76169380e+01,  1.21565646e+01, ...,
        -7.07378035e-02, -2.52142530e-02,  7.51651072e-03]])

In [45]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=0)

In [46]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()
model_rf.fit(X_train_pca, y_train)
model_rf.score(X_test_pca, y_test)

0.85

In [47]:
from sklearn.svm import SVC
model_svc = SVC()
model_svc.fit(X_train, y_train)
model_svc.score(X_test, y_test)

0.8777777777777778

In [48]:
model_svc.fit(X_train_pca, y_train)
model_svc.score(X_test_pca, y_test)

0.7222222222222222

In [51]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma="auto"), {
    "C": [1,10,20],
    "kernel": ["rbf", "linear", "poly"]
}, cv=5, return_train_score=False)
clf.fit(X_test_pca, y_test)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear', 'poly']})

In [52]:
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002582,4.822529e-04,0.001804,4.037689e-04,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.555556,0.500000,0.527778,0.500000,0.500000,0.516667,0.022222,7
1,0.530375,2.614491e-01,0.001000,4.004864e-06,1,linear,"{'C': 1, 'kernel': 'linear'}",0.916667,0.805556,0.805556,0.833333,0.944444,0.861111,0.058267,1
2,1.704204,1.095734e+00,0.000998,2.611745e-07,1,poly,"{'C': 1, 'kernel': 'poly'}",0.833333,0.805556,0.861111,0.750000,0.777778,0.805556,0.039284,4
3,0.001995,3.015783e-07,0.001396,4.885778e-04,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.555556,0.500000,0.527778,0.500000,0.500000,0.516667,0.022222,7
4,3.596562,2.298389e+00,0.000798,3.992084e-04,10,linear,"{'C': 10, 'kernel': 'linear'}",0.916667,0.805556,0.777778,0.833333,0.861111,0.838889,0.047791,2
5,2.301471,2.001031e+00,0.002392,3.314915e-03,10,poly,"{'C': 10, 'kernel': 'poly'}",0.833333,0.805556,0.861111,0.750000,0.777778,0.805556,0.039284,4
6,0.003988,8.919636e-04,0.002195,1.466213e-03,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.555556,0.500000,0.527778,0.500000,0.500000,0.516667,0.022222,7
7,5.811172,2.293062e+00,0.000998,4.623108e-07,20,linear,"{'C': 20, 'kernel': 'linear'}",0.888889,0.777778,0.777778,0.777778,0.861111,0.816667,0.048432,3
8,1.703615,1.082233e+00,0.000992,1.340701e-05,20,poly,"{'C': 20, 'kernel': 'poly'}",0.833333,0.805556,0.861111,0.750000,0.777778,0.805556,0.039284,4

In [53]:
df.mean_test_score.max()

0.861111111111111